services:
  tracker:
    build:
      context: .
    container_name: "tracker"
    restart: unless-stopped
    ports:
      - 8080:8080/udp
    environment:
      LISTEN_ADDRESS: 0.0.0.0
      LISTEN_PORT: 8080
      STATIC_PEERS: "127.0.0.1:8082"
      ANNOUNCE_INTERVAL: 600
      RUST_LOG: debug